# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: linx0344@cs.umn.edu
description: "Allen Y. Lin's Website"
baseurl: ""
url: "http://www-users.cs.umn.edu/~linx0344"
twitter_username: cheetah90
github_username:  cheetah90
facebook_username:  cheetah90

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
